name: Branch Cleanup

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string

jobs:
  branch-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.10.1
        with:
          egress-policy: audit
          
      - name: Delete release branch
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = '${{ inputs.branch_name }}';
            console.log(`Attempting to delete branch: ${branchName}`);
            try {
              await github.rest.git.deleteRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`
              });
              console.log(`Successfully deleted branch: ${branchName}`);
            } catch (error) {
              if (error.status === 422) {
                console.log(`Branch ${branchName} does not exist or has already been deleted.`);
              } else {
                console.error(`Error deleting branch ${branchName}:`, error);
                core.setFailed(`Failed to delete branch ${branchName}`);
              }
            }